### ISSUE TITLE
pipx not working

### ISSUE THREAD

**Issue by adelin-b** [b0g3r/plantuml2freemind#31]
Using pipx to punctually invoke this package is not working due to dependencies not included

```sh
pipx run plantuml2freemind

Traceback (most recent call last):
  File "/home/adelin/.local/pipx/.cache/af67d88f8226afa/bin/plantuml2freemind", line 5, in <module>
    from plantuml2freemind.cli import main
  File "/home/adelin/.local/pipx/.cache/af67d88f8226afa/lib/python3.8/site-packages/plantuml2freemind/cli.py", line 5, in <module>
    from plantuml2freemind.cli_commands import ConvertCommand
  File "/home/adelin/.local/pipx/.cache/af67d88f8226afa/lib/python3.8/site-packages/plantuml2freemind/cli_commands.py", line 5, in <module>
    from plantuml2freemind.generators import GENERATORS
  File "/home/adelin/.local/pipx/.cache/af67d88f8226afa/lib/python3.8/site-packages/plantuml2freemind/generators/__init__.py", line 7, in <module>
    from plantuml2freemind.generators.mapping import GENERATORS
  File "/home/adelin/.local/pipx/.cache/af67d88f8226afa/lib/python3.8/site-packages/plantuml2freemind/generators/mapping.py", line 3, in <module>
    from plantuml2freemind.custom_types import GeneratorType
  File "/home/adelin/.local/pipx/.cache/af67d88f8226afa/lib/python3.8/site-packages/plantuml2freemind/custom_types.py", line 5, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by b0g3r** [comment]
Oh-uh. Issue is confirmed, ETA of fix — 2 days

**Comment by b0g3r** [comment]
ETA is so ETA 😏 

I fixed the issue in [v0.8.1](https://pypi.org/project/plantuml2freemind/0.8.1/). Could you please check that issue was actually resolved?

**Comment by adelin-b** [comment]
Unfortunately same error with pipx

**Comment by adelin-b** [comment]
Maybe you can try a virgin docker get pipx and so you will see how it behave

**Comment by b0g3r** [comment]
In your case it could be a cache, try run `pipx install` with `--no-cache`. I cannot reproduce it in a clear docker environment:

``` 
# Dockerfile
FROM python:3.6

RUN pip install pipx
RUN pipx install plantuml2freemind && pipx ensurepath
RUN pipx run plantuml2freemind
```


<details>
  <summary>Build log with 3.6</summary>

  ```
Sending build context to Docker daemon  1.847MB
Step 1/4 : FROM python:3.6
 ---> 170e243861ec
Step 2/4 : RUN pip install pipx
 ---> Running in ffed93e3ec07
Collecting pipx
  Downloading pipx-0.15.6.0-py3-none-any.whl (43 kB)
Collecting packaging>=20.0
  Downloading packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting argcomplete<2.0,>=1.9.4
  Downloading argcomplete-1.12.1-py2.py3-none-any.whl (38 kB)
Collecting userpath>=1.4.1
  Downloading userpath-1.4.1-py2.py3-none-any.whl (14 kB)
Collecting six
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting importlib-metadata<3,>=0.23; python_version == "3.6"
  Downloading importlib_metadata-2.0.0-py2.py3-none-any.whl (31 kB)
Collecting click
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting distro; platform_system == "Linux"
  Downloading distro-1.5.0-py2.py3-none-any.whl (18 kB)
Collecting zipp>=0.5
  Downloading zipp-3.3.2-py3-none-any.whl (5.2 kB)
Installing collected packages: six, pyparsing, packaging, zipp, importlib-metadata, argcomplete, click, distro, userpath, pipx
Successfully installed argcomplete-1.12.1 click-7.1.2 distro-1.5.0 importlib-metadata-2.0.0 packaging-20.4 pipx-0.15.6.0 pyparsing-2.4.7 six-1.15.0 userpath-1.4.1 zipp-3.3.2
Removing intermediate container ffed93e3ec07
 ---> d2367612de1e
Step 3/4 : RUN pipx install plantuml2freemind && pipx ensurepath
 ---> Running in 509460e5377b
⚠️  Note: '/root/.local/bin' is not on your PATH environment variable. These apps will not be globally accessible until your PATH is updated. Run `pipx ensurepath` to automatically add it, or manually modify your PATH in your shell's config file (i.e. ~/.bashrc).
done! ✨ 🌟 ✨
creating virtual environment...
creating shared libraries...
upgrading shared libraries...
installing plantuml2freemind...
  installed package plantuml2freemind 0.8.2, Python 3.6.12
  These apps are now globally available
    - plantuml2freemind
Success! Added /root/.local/bin to the PATH environment variable.

Consider adding shell completions for pipx. Run 'pipx completions' for
instructions.

You will need to open a new terminal or re-login for the PATH changes
to take effect.

Otherwise pipx is ready to go! ✨ 🌟 ✨
Removing intermediate container 509460e5377b
 ---> d808baddf448
Step 4/4 : RUN pipx run plantuml2freemind
 ---> Running in 0f933d851fbf
Plantuml2Freemind version 0.8.2

USAGE
  plantuml2freemind [-h] [-q] [-v [<...>]] [-V] [--ansi] [--no-ansi] [-n]
                    <command> [<arg1>] ... [<argN>]

ARGUMENTS
  <command>              The command to execute
  <arg>                  The arguments of the command

GLOBAL OPTIONS
  -h (--help)            Display this help message
  -q (--quiet)           Do not output any message
  -v (--verbose)         Increase the verbosity of messages: "-v" for normal
                         output, "-vv" for more verbose output and "-vvv" for
                         debug
  -V (--version)         Display this application version
  --ansi                 Force ANSI output
  --no-ansi              Disable ANSI output
  -n (--no-interaction)  Do not ask any interactive question

AVAILABLE COMMANDS
  convert                Convert from one mindmap file format to another
                         format. Uses YAML tree file as intermediate format.
  help                   Display the manual of a command

creating virtual environment...
installing plantuml2freemind...
Removing intermediate container 0f933d851fbf
 ---> 5618c032530b
Successfully built 5618c032530b

  ```

</details>
